# This is a basic workflow to help you get started with Actions

name: Build and Publish to Github pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2.5.2

      # Runs a single command using the runners shell
      - name: Install Lilypond

        run: |
          curl https://lilypond.org/downloads/binaries/linux-x86/lilypond-2.23.6-1.linux-x86.sh | sh
          echo 'alias lilypond="/home/runner/bin/lilypond"' > /tmp/alias

      # Runs a set of commands using the runners shell
      - name: Install node dependencies
        run: npm ci

      - name: Bulild lilypond artifacts
        run: |
          source /tmp/alias
          npm run build:songs
      - name: Generate .md files for eleventy
        run: npm run build:pre-11ty
      - name: Build eleventy
        run: npm run build:11ty
